### ISSUE TITLE
How to use it the right way?

### ISSUE THREAD

**Issue by ueberBrot** [pawamoy/mkdocstrings#124]
Maybe I don't understand the documentation the right way but one of the appealing points for me to use this plugin is because of this statement:

> Sane defaults: you should be able to just drop the plugin in your configuration and enjoy your auto-generated docs.

I installed `mkdocstrings v0.11.4` + `mkdocs v1.1.2` and `mkdocs-material v5.2.3` with poetry in a virtual environment.

My project structure:

```ps
.
├── docs
│   ├── index.md
│   └── inherit.md
├── src
│   └── nacko_two
│       ├── __init__.py
│       └── inherit.py
├── tests
│   ├── __init__.py
│   └── test_nacko.py
├── mkdocs.yml
├── poetry.lock
└── pyproject.toml
```

I added the following configuration as stated in [the docs](https://pawamoy.github.io/mkdocstrings/#usage):

```yml
# mkdocs.yml
site_name: My Docs

nav:
  - Index: index.md
  - API: inherit.md


theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - src/nacko_two
```

I tried adding the docstrings from my file `inherit.py` in `inherit.md` the following way:

```md
# inherit.md
::: nacko_two.inherit
```

I use Google style docstrings.

When I now try and serve my documentation with `poetry run mkdocs serve` I get the [this error](https://gist.github.com/ueberBrot/d8646ba406c85c42c72ff70b470fd5ce). I pasted a gist here because its kinda long.

Now when I look in the [Troubleshooting](https://pawamoy.github.io/mkdocstrings/troubleshooting/#nothing-is-rendered-at-all) section of the documentation it says that you have to locally install your package to get docstring documentation from this plugin. Did I do something wrong or is this the only way to get the docstring documentation?

If a local installation of the package is required is there  a chance for an option where it is not necessary?  For example the [mkapi](https://github.com/daizutabi/mkapi/) plugin can create docstrings for the docs without a local installation.
