### ISSUE TITLE
Show full path only for direct children of a module

### ISSUE THREAD

**Issue by adunmore** [pawamoy/mkdocstrings#134]
**Is your feature request related to a problem? Please describe.**

When I write a document page that includes multiple objects from a module, it would be nice to be able to include full paths only for the module's direct children.

The current renderer options aren't flexible enough for what I'm trying to do:

`show_root_full_path` results in a document that doesn't show object paths as often as I'd like. This is particularly harmful to usability when a document represents a module with many members. In this case, a single reference to the module path can be buried in a long document.

`show_object_full_path` shows too much. For example, when a class's path is already shown, it seems redundant to show the full paths of all its methods and attributes.

**Describe the solution you'd like**

A rendering option that would only include full object paths for the direct children of a module.

**Describe alternatives you've considered**

One option is to
- use `show_root_heading`
- manually identify all of a module's children

But this seems unnecessarily laborious, especially when documenting large modules.

**Additional context**
Example: 

For some module with the structure
```
- module
  - class_1
    - method_1
    - method_2
```

**Bad option 1:**
```
:::path.to.module
    rendering:
        show_root_heading: true
        show_root_full_path: true
```
Results in something like

```
path.to.module
  class_1
    method_1()
    method_2()
# too sparse
```

**Bad option 2:**
```
:::path.to.module
    rendering:
        show_object_full_path: true
        show_root_heading: true
```
Results in something like
```
path.to.module.class_1
  path.to.module.class_1.method_1()
  path.to.module.class_1.method_2()
# too verbose
```

**What I'd like:**
```
:::path.to.module
    rendering:
        option_for_perfect_full_paths: true
        show_root_headers: false
```
Resulting in
```
path.to.module.class_1
  method_1()
  method_2()
# just right :)
```

**Comment by pawamoy** [comment]
Hello, thanks for the detailed feature request :slightly_smiling_face: 

So, if you have this:

```
module
  Class1
    method_a
  Class2
    method_b
```

and

```
::: path.to.module
    rendering:
      option_for_perfect_full_paths: true
      show_root_heading: false
```

You want to see

```
Module docstring.

path.to.module.Class1
  Class1 docstring.

  method_a()
    Method A docstring.

path.to.module.Class2
  Class2 docstring.

  method_b()
    Method B docstring.
```

Did I get this right?

Well this is a fair request, it shouldn't be too hard to implement. Do you want to try and send a PR?
We could call the option `show_root_members_full_path`. Then in the template you'd do something like:

```jinja2
      {% if root %}
        {% set show_full_path = config.show_root_full_path %}
        {% set root_members = True %}
      {% elif root_members %}
        {% set show_full_path = config.show_root_members_full_path %}
        {% set root_members = False %}
      {% else %}
        {% set show_full_path = config.show_object_full_path %}
      {% endif %}
```

**Comment by StephenBrown2** [comment]
And config would look like:
```yaml
    rendering:
      show_root_full_path: true
      show_root_members_full_path: false
      show_root_heading: false
```
?
