### ISSUE TITLE
mkdocstrings.plugin: configuration item 'site_url' is required for cross-references

### ISSUE THREAD

**Issue by nicolasfauchereau** [pawamoy/mkdocstrings#147]
Hi and apologies if this is not the place to ask, but I was not able to find the answer in the documentation or using google search 

I am playing with mkdocs (version 1.1.2) and mkdocstrings (version 0.13.0) to try and document a small project (early stage of development) and I am getting this error message 

`mkdocstrings.plugin: configuration item 'site_url' is required for cross-references`

every time I try and run `mkdocs build`

The structure of the project is below, the content of the `mkdocs.yml` file is 
```
site_name: dl4seas

theme:
  name: "material"
  palette:
    primary: lime
  features:
    - instant
    - navigation.expand

plugins:
  - search
  - mkdocstrings

repo_url: https://github.com/nicolasfauchereau/dl4seas

nav:
    - Home: index.md
    - Installation: installation.md
    - Code Reference:
        - utils: utils-reference.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nfauchereau
    - icon: fontawesome/brands/github
      link: https://github.com/nicolasfauchereau

```
structure 
.
├── docs
│   ├── index.md
│   ├── installation.md
│   └── utils-reference.md
├── __init__.py
├── IO
│   ├── __init__.py
│   ├── netcdf_to_TF_records.py
│   └── xarray_to_TF_record.py
├── mkdocs.yml
├── NN
│   ├── __init__.py
│   ├── PeriodicConv2D.py
│   ├── PeriodicPadding2D.py
│   ├── PrunePeriodicPadding2D.py
│   ├── __pycache__
│   ├── ResizeLayer.py
│   └── XrDataGenerator.py
├── preprocessing
│   ├── __init__.py
│   └── train_scaler.py
├── __pycache__
│   └── __init__.cpython-37.pyc
├── setup.py
└── utils
    ├── __init__.py
    ├── list_files.py
    ├── __pycache__
    ├── roll_longitudes.py
    └── shift_time.py
