### ISSUE TITLE
use_directory_urls: false breaks references from the parent directory

### ISSUE THREAD

**Issue by mRokita** [pawamoy/mkdocstrings#149]
**Describe the bug**

References skip the base directory - instead of https://site/a/thisshouldbehere/reference/main.html#module.main.SomeClass it links https://site/a/reference/main.html#module.main.SomeClass

**Expected behavior**

reference/main.html#module.main.SomeClass 

instead of

../reference/main.html#module.main.SomeClass

**To Reproduce**

Use the following mkdocs.yml and reference something from main.md in index.md.

```yml
use_directory_urls: false
site_name: "site"
site_dir: "./public"
repo_name: "mrokita/site"

nav:
  - Introduction: index.md
  - Reference:
      - main.py: reference/main.md
markdown_extensions:
  - toc:
      permalink: true
  - toc:
      permalink: true
  - codehilite:
      linenums: true
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.details
theme:
  name: "material"
  language: pl
  palette:
    primary: white
    accent: blue
extra_css:
  - css/mkdocstrings.css
plugins:
  - search
  - mkdocstrings:
      watch:
        - app
      handlers:
        python:
          selection:
            filters:
              - "!^__"
              - "!^__config__"
              - "!^__json_encoder__"
          rendering:
            show_if_no_docstring: true
```
**Dependencies**

mkdocstrings == 0.13.1
pytkdocs == 0.7.0
