### ISSUE TITLE
Incorrect rendering of functions from different modules with global `show_root_heading: false`

### ISSUE THREAD

**Issue by chrieke** [pawamoy/mkdocstrings#156]
**Describe the bug**
Incorrect rendering when having functions of two different modules in the markdown and setting global `show_root_heading: false` in the mkdocs.yml file.

Markdown file:
```
::: up42.tools.Tools.plot_results

::: up42.job.Job
```

mkdocs.yml:

```
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_category_heading: true
            show_source: true

```

This leads to an incorrect rendering where the `up42.tools.Tools.plot_results` function is missing a heading (see screenshot section). For `show_root_heading: true` it work correctly.

**Expected behavior**
Correct rendering also with `show_root_heading: false`, showing the header.

**Screenshots**
`show_root_heading: false`: incorrect rendering

![image](https://user-images.githubusercontent.com/12833517/94361377-161c5180-00b4-11eb-90a0-4231241ddd79.png)

`show_root_heading: true`:

![image](https://user-images.githubusercontent.com/12833517/94361413-61366480-00b4-11eb-83b7-f6e9473f14d3.png)

**Information (please complete the following information):**
- OS: Catalina 10.15.06
- Browser: Chrome 85.0.4
- `mkdocstrings` version: 0.13.4
