### ISSUE TITLE
Footnote appears in all following objects after the first appearance

### ISSUE THREAD

**Issue by anthonyhtyao** [pawamoy/mkdocstrings#186]
Hi, I'm not sure this is related to pytkdocs or mkdocstrings.

**Describe the bug**
If a footnote is added to one of python objects, the footnote will appear in every object after that one in the same documentation page.  

**To Reproduce**
Here is an example to reproduce

```python
# example.py
def C():
    """This is C
    """
    pass

def B():
    """This is B[^1]

    [^1]: This is footnote
    """
    pass

def A():
    """This is A
    """
    pass
````
```
# mkdocs.yml
site_name: Footnote
theme:
  name: "material"
plugins:
  - search
  - mkdocstrings:
      default_handler: python
markdown_extensions:
  - footnotes
```
**Expected behavior**
The footnote is supposed to appear only under function B

**Screenshots**
However, footnote appears under function B and C

[
![Screenshot from 2020-12-05 00-30-54](https://user-images.githubusercontent.com/13106293/101225955-25f77980-3693-11eb-85af-291a6cb55777.png)
](url)
