### ISSUE TITLE
Configuration for pytkdocs `filter` option?

### ISSUE THREAD

**Issue by StephenBrown2** [pawamoy/mkdocstrings#62]
I see that pytkdocs has a single configuration option, though it's unclear where I can set that helpful regex in the `mkdocs.yml` under mkdocstrings. I've got a special class function that I don't really want in the generated docs.

**Comment by pawamoy** [comment]
Indeed there's a `filterd` option in `pytkdocs`, and I forgot to tell in the 0.9.0 release changelog that the `global_filters` key was removed from `mkdocstrings` (sorry if you were using it!)

I wanted to get some feedback/input first, before adding selection options to the Python collector. There is some discussion in #44 already, and I'd love to have your feedback as well :slightly_smiling_face:

**Comment by pawamoy** [comment]
Released 0.10.0, closing!

To filter out private members (which is now the default again):

```
::: pkg.mod.obj
    selection:
      filters:
        - "!^_[^_]"
```

Or globally in `mkdocs.yml`:

```
plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "!^_[^_]"
```
