### ISSUE TITLE
Allow setting default handler options in top keys of plugins.mkdocstrings in mkdocs.yml

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/mkdocstrings#63]
Currently, to define global selection and rendering for the Python handler, one has to write:

```yaml
plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "!^_[^_]"
          rendering:
            option1: etc
```

Since we have a `default_handler` option, we could support setting `selection` and `rendering` like this:

```yaml
plugins:
  - mkdocstrings:
      selection:
        filters:
          - "!^_[^_]"
      rendering:
        option1: etc
```

In this case, since the default `default_handler` is Python, these options apply for it.

With

```yaml
plugins:
  - mkdocstrings:
      default_handler: rust
      selection:
        option1: etc
      rendering:
        option1: etc
```

...they would apply for the Rust handler.
