### ISSUE TITLE
Methods without a docstring do not get rendered

### ISSUE THREAD

**Issue by ofek** [pawamoy/mkdocstrings#64]
### Setup

`mkdocstrings` version `0.10.0`
Python 3.8.1
Windows 10

### Description

This

```
::: datadog_checks.base.stubs.datadog_agent.DatadogAgentStub
```

renders this

https://github.com/DataDog/integrations-core/blob/hack-a-doc/datadog_checks_base/datadog_checks/base/stubs/datadog_agent.py#L6

as nothing:

```html
<h6 class=hidden-toc href=#datadog_checks.base.stubs.datadog_agent.DatadogAgentStub id=datadog_checks.base.stubs.datadog_agent.DatadogAgentStub style="visibility: hidden; width: 0; height: 0;"> <a class=headerlink href=#datadog_checks.base.stubs.datadog_agent.DatadogAgentStub title="Permanent link">¶</a></h6>
```

If I add a class docstring then I get the text but the anchor is still hidden (and no members of course b/c no docstrings).

I'd expect the linked code to look something like we have here (with https://github.com/tomchristie/mkautodoc):

https://datadoghq.dev/integrations-core/base/api/#datadog-agent

**Comment by ofek** [comment]
Hmm, I guess that's 2 issues actually

**Comment by pawamoy** [comment]
Try using these two options:

```
::: datadog_checks.base.stubs.datadog_agent.DatadogAgentStub
    rendering:
      show_root_heading: yes
      show_if_no_docstring: yes
```

You set these as default in `mkdocs.yml`:

```
plugins:
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: yes
            show_if_no_docstring: yes
```

All the options: https://pawamoy.github.io/mkdocstrings/reference/handlers/python/#mkdocstrings.handlers.python.PythonRenderer.DEFAULT_CONFIG
