### ISSUE TITLE
TOC broken when selecting non-modules

### ISSUE THREAD

**Issue by ofek** [pawamoy/mkdocstrings#65]
```
# API

-----

::: datadog_checks.base.AgentCheck
    selection:
      members:
        - gauge
        - count
        - monotonic_count
        - rate
        - histogram
        - historate
        - service_check
        - event

::: datadog_checks.base.stubs.aggregator.AggregatorStub
    selection:
      members:
        - assert_metric
        - assert_metric_has_tag
        - assert_metric_has_tag_prefix
        - assert_service_check
        - assert_event
        - assert_all_metrics_covered
        - assert_no_duplicate_metrics
        - assert_no_duplicate_service_checks
        - assert_no_duplicate_all
        - reset

::: datadog_checks.base.stubs.datadog_agent.DatadogAgentStub
```

![Capture](https://user-images.githubusercontent.com/9677399/77834490-6faebe00-711b-11ea-820e-379304e7196b.PNG)

**Comment by pawamoy** [comment]
Try this:

```
# API

-----

::: datadog_checks.base.AgentCheck
    rendering:
      show_root_heading: true
    selection:
      members:
        - gauge
        - count
        - monotonic_count
        - rate
        - histogram
        - historate
        - service_check
        - event

::: datadog_checks.base.stubs.aggregator.AggregatorStub
    rendering:
      show_root_heading: true
    selection:
      members:
        - assert_metric
        - assert_metric_has_tag
        - assert_metric_has_tag_prefix
        - assert_service_check
        - assert_event
        - assert_all_metrics_covered
        - assert_no_duplicate_metrics
        - assert_no_duplicate_service_checks
        - assert_no_duplicate_all
        - reset

::: datadog_checks.base.stubs.datadog_agent.DatadogAgentStub
    rendering:
      show_root_heading: true
```

Here's how the template works:

- if `show_root_heading` is true, show the top object heading
- if `show_root_heading` is false, you still have a chance to add the object to the ToC with `show_root_toc_entry` set to true. Adding the ToC entry is required for cross-references to this object to work.

However I agree that the ToC seems broken: it's because I used `h6` for the hidden ToC entries. I think it would be best to use the specified heading level.
