### ISSUE TITLE
better error message when plugin fails

### ISSUE THREAD

**Issue by koaning** [pawamoy/mkdocstrings#85]
I wanted to release a new open source package today (over [here](https://github.com/RasaHQ/whatlies/)), but unfortunately find that I can no longer update the documentation. I see a lot of new version updates recently on pypi so I think that may be the reason why. 

**Describe the bug**

I am running python3.7 locally. With these versions installed; 

```
> python --version
Python 3.7.7
> python -m pip freeze | grep mkdocs
mkdocs==1.1
mkdocs-material==5.1.0
mkdocs-material-extensions==1.0b1
mkdocstrings==0.10.3
```

This is the basic `mkdocs.yml` file, but when I run this there is no source code being shown (this was different a few weeks ago).

```
plugins:
  - mkdocstrings
  - search
```

This is what it looks like; 

![image](https://user-images.githubusercontent.com/1019791/79195863-4e461580-7e2f-11ea-85b6-dbdadb42712e.png)

This is what it should look like; 

![image](https://user-images.githubusercontent.com/1019791/79196084-b0067f80-7e2f-11ea-92c0-2ff2daa96185.png)

So instead I've taken the new config that I found on this projects documentation. 

```
plugins:
  - mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: true
    watch:
      - whatlies
  - search
```

The name of the package is `whatlies` so this should work, but unfortunately I get this error; 
```
> mkdocs serve
ERROR   -  Config value: 'plugins'. Error: Invalid Plugins configuration 
```

**Expected behavior**

No errors.

**Comment by koaning** [comment]
To anybody interested, if you want the original settings to still show the source code, you can do so by hard coding these versions; 

```
mkdocs==1.1
mkdocs-material==4.6.3
mkdocstrings==0.8.0
```

**Comment by pawamoy** [comment]
A kinda big refactor happened from mkdocstrings 0.8 to 0.9. The design changed a bit.

I don't see any failure in your first screenshot. To explain, here are the things that changed:

- the source code is displayed *after* the docstring now. This is because showing it before was messing up the search display. See #35.
- the table cells have margins/paddings. This is because we do not render markdown tables anymore, but rather markdown paragraphs in HTML table cells. The material theme has some CSS rules that adds these margins/paddings to `<p>` tags, impacting our table cells. There is no way to prevent the Markdown library from wrapping the text into `<p>` when converting it, though you can fix it with CSS rules: see https://pawamoy.github.io/mkdocstrings/handlers/python/#recommended-style
- by default, the root object header is not shown, and a hidden toc entry is added instead. This is configurable through the Python renderer options: see https://pawamoy.github.io/mkdocstrings/reference/handlers/python/#mkdocstrings.handlers.python.PythonRenderer.DEFAULT_CONFIG
- finally, the `special` property now appears next to special methods or special modules (whose names are like `__something__`). This is not configurable.

If there are other changes I didn't spot, just tell me, I'll try to explain them :slightly_smiling_face: 

Now for the last part, I think your indentation is wrong. This is one of the tricky things with YAML:

With the following YAML:

```yaml
plugins:
  - mkdocstrings:
    default_handler: python  # same indentation
    handlers:
      python:
        rendering:
          show_source: true
    watch:
      - whatlies
  - search
```

...you'll get the following equivalent Python dictionary:

```python
{
    "plugins": [
        {
            "mkdocstrings": {},
            "default_handler": "python",
            "handlers": {...},
            "watch": ["whatlies"]
        },
        "search"
    ]
}
```

...which MkDocs cannot use.

Instead, you should write:

```yaml
plugins:
  - mkdocstrings:
      default_handler: python  # two more spaces of indentation
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - whatlies
  - search
```

...which will give the correct:

```python
{
    "plugins": [
        {
            "mkdocstrings": {
                "default_handler": "python",
                "handlers": {...},
                "watch": ["whatlies"]
            }
        },
        "search"
    ]
}
```

Closing since there's no bug here :slightly_smiling_face:
